### PR TITLE
fixed #6.

### LINKED ISSUE #6: Bug: throwing error when define argumentNames with double quotes
```dart
@FFRoute(
  name: 'rexiapp://sms-confirm',
  routeName: 'sms-confirm',
  argumentNames: ['phoneNumber'],
)
```
```
FormatException: Unexpected character (at character 2)
['phoneNumber']
```

### PR DESCRIPTION
**Pull request by iota9star**

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
测试过了？ 看起来不错。

File: lib/src/route_generator.dart [hunk 1]
```diff
@@ -84,28 +84,41 @@ class RouteGenerator {
...
+                        break;
+                      case 'routeName:':
+                        routeName = source;
+                        break;
+                      case 'showStatusBar:':
+                        showStatusBar = source == 'true';
+                        break;
+                      case 'argumentNames:':
+                        argumentNames = source
+                            .replaceAll(RegExp('\\[|\\]'), '')
```
Comment (AlexV525) [inline lib/src/route_generator.dart:111]: By changing the rules to reg expression, please make sure everywhere would be using the same rules, (e.g. route names and constants) or there would be worse if those methods using different rules to generate route and cause unexpected result.

确保每一处都使用同样的解析规则（例：路由名字数组、常量），否则使用未统一的解析规则会导致无可预料的结果。

Comment (AlexV525) [reply lib/src/route_generator.dart:111]: Such as
https://github.com/fluttercandies/ff_annotation_route/blob/5c5d1a899292d2a6f9443bc56f187db985800400/lib/src/route_generator.dart#L180-L183

https://github.com/fluttercandies/ff_annotation_route/blob/5c5d1a899292d2a6f9443bc56f187db985800400/lib/src/route_generator.dart#L227-L233

**Review by AlexV525 — CHANGES_REQUESTED** [review]
